name: GitHub Readme Stats
on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12 horas
  workflow_dispatch: # Permite rodar manualmente
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats
        uses: stats-organization/github-readme-stats-action@v1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: generated
          username: IagoDSN
          theme: radical
          show_icons: true
          include_all_commits: true
